### ISSUE TITLE
NoClassDefFoundError: org/bouncycastle/jcajce/provider/digest/Keccak$Digest384

### ISSUE THREAD

**Issue by xiaoGreaat** [iotaledger/iota.lib.java#105]
IotaAPI api = new IotaAPI.Builder().build();
        GetNodeInfoResponse response = api.getNodeInfo();
        System.out.println(response.toString());

NoClassDefFoundError: org/bouncycastle/jcajce/provider/digest/Keccak$Digest384
why？

**Comment by TestTokenGenerator** [comment]
same here, seems like something in the dependencies is missing?

**Comment by kwek20** [comment]
@xiaoGreaat Am I correct that you compiled the repository and linked to the generated jar, instead of importing through maven/gradle? If that is the case you should compile "jota-parent" with the profile "release", and link to the generated jar.

It should look like the following:
jota-[version]-jar-with-dependencies.jar

I will update the documentation for this on the main page.
Thank you for informing us the instructions are not clear enough.

**Comment by kwek20** [comment]
Hey! 

Just an update, since we switched to multi-module build, the jitpack dependency automatically links to the one without dependencies included.

A fix is on the way!

**Comment by kwek20** [comment]
Hey @xiaoGreaat @TestTokenGenerator 
I have updated the maven instructions in the README. 
Our default jar is exported with just our classes, and no dependencies.
If you wish to get the dependencies jar instead, add the following to your `<dependency>`
`<classifier>jar-with-dependencies</classifier>`

Example:
```
<dependency>
    <groupId>com.github.iotaledger.iota~lib~java</groupId>
    <artifactId>jota</artifactId>
    <classifier>jar-with-dependencies</classifier>
    <version>17e0de8ed5</version>
</dependency>
```

You can replace the version with any other hash (first 10 characters), or a release tag. 

Please let me know if you have any questions!
