### ISSUE TITLE
"Invalid API Version" after update to IRI 1.4.1

### ISSUE THREAD

**Issue by france193** [iotaledger/iota.lib.java#47]
Exception in thread "main" java.lang.IllegalAccessError: 400 {"error":"Invalid API Version","duration":0}
	at jota.IotaAPICore.wrapCheckedException(IotaAPICore.java:58)
	at jota.IotaAPICore.getNodeInfo(IotaAPICore.java:111)
	at france193.IOTANode.getNodeInfo(IOTANode.java:59)
	at france193.Main.main(Main.java:19)

**Comment by th0br0** [comment]
Fixed by 0.9.6

**Comment by Komhar** [comment]
Same issue on IRI 1.4.1.1, X-IOTA-API-Version not mandatory in the API reference, but com.iota.iri.service.API.java :: processRequest() -> processRequest has:

```
 if (exchange.getRequestHeaders().contains("X-IOTA-API-Version")) {
            response = process(body, exchange.getSourceAddress());
        } else {
            response = ErrorResponse.create("Invalid API Version");
  }
```
Removing the check on local to move ahead...

**Comment by adeepi** [comment]
getNodeInfo still giving {"error":"Invalid API Version","duration":10} in IRI 1.4.1.2 on Ubuntu

**Comment by SatoshiReport** [comment]
Same issue here with getNodeInfo still giving {"error":"Invalid API Version","duration":10} in IRI 1.4.1.2 on Ubuntu

**Comment by SatoshiReport** [comment]
The problem for me was that I was doing in invalid call however it always returned the same false error of "Invalid API Version"

In  iri/src/main/java/com/iota/iri/service/API.java it says

`        if (!exchange.getRequestHeaders().contains("X-IOTA-API-Version")) {
response = ErrorResponse.create("Invalid API Version");`

So if you do not contain the header in the request (my issue) it states "Invalid API Version" instead of "Missing API Version".
